name: CI

on:
  push:
  schedule:
    - cron: '0 6 * * *'

jobs:
  run:
    name: Hydat-Forge Data Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Setup Python
      - uses: actions/setup-python@v2.1.3
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: era5-forge
          environment-file: .binder/environment.yml
          python-version: 3.8
          auto-activate-base: false
      - name: Configure AWS keys (Wasabi Sys.)
        run: |
            mkdir -p ~/.aws
            touch ~/.aws/credentials
            echo "
            [default]
            aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key = ${{ secrets.AWS_SECRET_KEY_ID }}
            region = us-east-2
            source_profile = default" > ~/.aws/credentials

            touch ~/.cdsapirc
            echo "
            url: https://cds.climate.copernicus.eu/api/v2
            key: ${{ secrets.CDS_API_KEY }}
            " > ~/.cdsapirc

      - name: Run Pipeline
        run: |

            # Register flow
            python pipeline.py